site_name: Praxis AI Documentation
   theme:
     name: material
   nav:
     - Home: index.md
     - User Guide:
         - Getting Started: user-guide/getting-started.md
     - API Reference:
         - Overview: api-reference/overview.md
     - Development:
         - Contributing: development/contributing.md